name: Api redeploy

on:
  push:
    branches: [ "master" ]
    paths: ["Api/**"]
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Navigating to ./Api
      run: cd /home/ubuntu/Mutual/Api && pwd && ls
    - name: Rebuilding
      run: bash run.sh
