name: Api redeploy

on:
  push:
    branches: [ "master" ]
    paths: ["Api/**"]
  workflow_dispatch:

jobs:
  api-redeploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: rebuilding
      working-directory: /home/ubuntu/Mutual/Api
      run: bash run.sh
