name: Frontend.Web redeploy

on:
  push:
    branches: [ "master" ]
    paths: ["Frontend/Frontend.Web/**", "Frontend/Frontend.Shared/**"]
  workflow_dispatch:

jobs:
  frontend-redeploy:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: rebuilding
      working-directory: /home/ubuntu/Mutual/Frontend/Frontend.Web/
      run: bash run.sh
